/**
 * Agent knowledge file — a concise, grounded projection of the model for the
 * coding agents that read a repo context file (AGENTS.md) rather than MCP.
 *
 * Written into a *managed block* so hand-authored notes around it survive, and
 * regenerated on every `analyze`/`update` so it never drifts from the code.
 * Keep it compact: it's loaded into the agent's context every turn.
 */
import { type ArchitectureModel } from "../ir/types.js";
import { groupCapabilities } from "./capability.js";

export const KNOWLEDGE_START = "<!-- archmantic:start -->";
export const KNOWLEDGE_END = "<!-- archmantic:end -->";

const refOf = (el: { provenance: { ref: string }[] }) => el.provenance[0]?.ref ?? "?";

export function knowledgeMarkdown(model: ArchitectureModel): string {
  const internal = model.systems.find((s) => s.kind === "internal");
  const externals = model.systems.filter((s) => s.kind === "external").map((s) => s.name);
  const out: string[] = [];

  out.push("## Architecture (Archmantic)");
  out.push("");
  out.push("> Auto-generated from the grounded architecture model — do not edit inside this block. Refresh with `amt knowledge`.");
  out.push("");
  out.push(`**${model.project}**${internal?.description ? ` — ${internal.description}` : ""}`);
  out.push("");
  out.push(
    `${model.components.length} components · ${model.capabilities.length} capabilities · ` +
      `${model.endpoints?.length ?? 0} endpoints · ${model.dataEntities?.length ?? 0} data entities.`,
  );

  const groups = groupCapabilities(model);
  if (groups.length) {
    out.push("");
    out.push("### What it does (capabilities)");
    let shown = 0;
    const CAP = 40;
    for (const g of groups) {
      if (shown >= CAP) break;
      const names = g.capabilities.slice(0, CAP - shown).map((c) => c.name);
      shown += names.length;
      out.push(`- **${g.area}/** — ${names.join(", ")}`);
    }
    if (model.capabilities.length > shown) out.push(`- …and ${model.capabilities.length - shown} more`);
  }

  if (model.dataEntities?.length) {
    out.push("");
    out.push("### Data model");
    for (const e of model.dataEntities.slice(0, 30)) {
      const cols = e.fields.filter((f) => !(f.relationTo && !f.isForeignKey)).map((f) => f.name);
      const rels = e.fields.filter((f) => f.relationTo).map((f) => `→${f.type}`);
      out.push(`- **${e.name}** <sub>${refOf(e)}</sub>: ${cols.join(", ")}${rels.length ? `  ${rels.join(" ")}` : ""}`);
    }
    if (model.dataEntities.length > 30) out.push(`- …and ${model.dataEntities.length - 30} more`);
  }

  if (model.endpoints?.length) {
    out.push("");
    out.push("### API surface");
    for (const ep of model.endpoints.slice(0, 50)) out.push(`- \`${ep.method} ${ep.path}\` (${ep.protocol})`);
    if (model.endpoints.length > 50) out.push(`- …and ${model.endpoints.length - 50} more`);
  }

  const proc = model.processes?.[0];
  if (proc) {
    out.push("");
    out.push(`### Primary process: ${proc.name}`);
    out.push(proc.tasks.map((t) => t.name).join(" → "));
  }

  if (externals.length) {
    out.push("");
    out.push(`**External systems:** ${externals.join(", ")}`);
  }
  if (model.technologies?.length) {
    const byCat = new Map<string, string[]>();
    for (const t of model.technologies) (byCat.get(t.category) ?? byCat.set(t.category, []).get(t.category)!).push(t.name);
    out.push("");
    out.push("**Stack:** " + [...byCat.entries()].sort().map(([c, n]) => `${c}: ${n.join("/")}`).join(" · "));
  }

  out.push("");
  out.push("_Full detail: `amt view` (diagrams + trust) or the Archmantic MCP server (`get_context`, `get_component`, `get_api_surface`, …)._");
  return out.join("\n");
}

/** Insert or replace the managed block in `existing` (preserving content around it). */
export function applyKnowledgeBlock(existing: string | null, body: string): string {
  const block = `${KNOWLEDGE_START}\n${body}\n${KNOWLEDGE_END}`;
  if (existing) {
    const s = existing.indexOf(KNOWLEDGE_START);
    const e = existing.indexOf(KNOWLEDGE_END);
    if (s !== -1 && e !== -1 && e > s) {
      return existing.slice(0, s) + block + existing.slice(e + KNOWLEDGE_END.length);
    }
    if (existing.trim()) return existing.trimEnd() + "\n\n" + block + "\n";
  }
  return `# AGENTS\n\nProject context for AI coding agents. The block below is generated by Archmantic.\n\n${block}\n`;
}
