/**
 * Build-spec emitter — project the architecture model into an agent-consumable
 * "build spec": what the system should be (capabilities, components,
 * responsibilities, dependencies, processes), grounded in `file:line`.
 *
 * This is the bridge of the edit-then-build loop: edit the model (capabilities,
 * the BPMN process), emit a spec, and hand it to an external coding agent (e.g.
 * Claude Code) to implement or verify. Markdown for humans/agents, JSON for
 * programmatic consumers. Pure projection over the IR.
 */
import { type ArchitectureModel } from "../ir/types.js";
import { componentLabel } from "../ir/naming.js";
import { groupCapabilities } from "./capability.js";

const rel = (id: string) => id.slice(id.indexOf(":") + 1);
const refOf = (el: { provenance: { ref: string }[] }) => el.provenance[0]?.ref ?? "?";

function shortTarget(id: string): string {
  if (id.startsWith("comp:")) return componentLabel(id);
  if (id.startsWith("sys:ext:")) return id.slice("sys:ext:".length);
  return id;
}

export function buildSpecMarkdown(model: ArchitectureModel): string {
  const internal = model.systems.find((s) => s.kind === "internal");
  const externals = model.systems.filter((s) => s.kind === "external");
  const internalDeps = model.relations.filter((r) => r.to.startsWith("comp:")).length;
  const out: string[] = [];

  out.push(`# Build Spec — ${model.project}`);
  out.push("");
  out.push(
    `> Generated by Archmantic from the architecture model${model.generatedAt ? ` (${model.generatedAt})` : ""}. ` +
      `Every item is grounded in a code reference. Hand this to a coding agent to implement or verify the system.`,
  );
  out.push("");
  out.push("## Overview");
  out.push("");
  out.push(`${internal?.description ?? model.project}`);
  out.push("");
  out.push(
    `- **${model.components.length}** components, **${internalDeps}** internal dependencies, ` +
      `**${model.capabilities.length}** capabilities, **${model.processes.length}** process(es).`,
  );
  out.push(`- **External systems:** ${externals.map((s) => s.name).join(", ") || "none"}`);

  if (model.technologies?.length) {
    out.push("");
    out.push("## Tech stack");
    out.push("");
    const byCat = new Map<string, string[]>();
    for (const t of model.technologies) (byCat.get(t.category) ?? byCat.set(t.category, []).get(t.category)!).push(t.name);
    for (const [cat, names] of [...byCat.entries()].sort()) out.push(`- **${cat}:** ${names.join(", ")}`);
  }

  if (model.dataEntities?.length) {
    out.push("");
    out.push("## Data model");
    out.push("");
    for (const e of model.dataEntities) {
      out.push(`### ${e.name} <sub>\`${refOf(e)}\`</sub>`);
      for (const f of e.fields) {
        if (f.relationTo && !f.isForeignKey) continue; // pure nav field → shown as relation below
        const tags = [f.isId ? "PK" : "", f.isForeignKey ? "FK" : "", f.isUnique && !f.isId ? "unique" : ""]
          .filter(Boolean)
          .join(", ");
        out.push(`- ${f.name}: ${f.type}${f.list ? "[]" : ""}${f.optional ? "?" : ""}${tags ? ` (${tags})` : ""}`);
      }
      for (const f of e.fields.filter((f) => f.relationTo)) {
        out.push(`- → ${f.name}: ${f.type}${f.list ? "[]" : ""} _(relation)_`);
      }
      out.push("");
    }
  }

  out.push("");
  out.push("## Capabilities to implement");
  out.push("");
  const groups = groupCapabilities(model);
  if (!groups.length) out.push("_None derived._");
  for (const g of groups) {
    out.push(`### ${g.area}/`);
    for (const cap of g.capabilities) {
      out.push(`- **${cap.name}** — ${cap.description ?? "(no description)"} <sub>\`${refOf(cap)}\`</sub>`);
    }
    out.push("");
  }

  out.push("## Components");
  out.push("");
  for (const c of model.components) {
    const deps = model.relations.filter((r) => r.from === c.id).map((r) => shortTarget(r.to));
    const implals = model.capabilities.filter((cap) => cap.componentIds.includes(c.id)).map((cap) => cap.name);
    out.push(`### ${componentLabel(c.id)} \`${rel(c.id)}\``);
    if (c.responsibility) out.push(`- Responsibility: ${c.responsibility}`);
    out.push(`- Depends on: ${deps.length ? deps.join(", ") : "—"}`);
    if (implals.length) out.push(`- Implements: ${implals.join(", ")}`);
    out.push("");
  }

  const proc = model.processes[0];
  if (proc) {
    out.push("## Process");
    out.push("");
    out.push(`**${proc.name}**${proc.description ? ` — ${proc.description}` : ""}`);
    out.push("");
    out.push(proc.tasks.map((t, i) => `${i + 1}. ${t.name}`).join("\n"));
    out.push("");
  }

  out.push("---");
  out.push(`<sub>Archmantic build spec · ${model.components.length} components · grounded in code.</sub>`);
  return out.join("\n");
}

export interface BuildSpecJson {
  project: string;
  generatedAt?: string;
  overview: { components: number; internalDependencies: number; capabilities: number; externals: string[] };
  technologies: { name: string; category: string }[];
  capabilities: { name: string; description?: string; ref: string; components: string[] }[];
  components: { id: string; label: string; path: string; responsibility?: string; dependsOn: string[]; implements: string[] }[];
  dataModel: {
    name: string;
    ref: string;
    fields: { name: string; type: string; optional?: boolean; list?: boolean; key?: "PK" | "FK" | "UK" }[];
    relations: { field: string; to: string; list?: boolean }[];
  }[];
  process?: { name: string; description?: string; steps: string[] };
}

export function buildSpecJson(model: ArchitectureModel): BuildSpecJson {
  const externals = model.systems.filter((s) => s.kind === "external");
  const proc = model.processes[0];
  return {
    project: model.project,
    generatedAt: model.generatedAt,
    overview: {
      components: model.components.length,
      internalDependencies: model.relations.filter((r) => r.to.startsWith("comp:")).length,
      capabilities: model.capabilities.length,
      externals: externals.map((s) => s.name),
    },
    technologies: (model.technologies ?? []).map((t) => ({ name: t.name, category: t.category })),
    capabilities: model.capabilities.map((cap) => ({
      name: cap.name,
      description: cap.description,
      ref: refOf(cap),
      components: cap.componentIds.map(shortTarget),
    })),
    components: model.components.map((c) => ({
      id: c.id,
      label: componentLabel(c.id),
      path: rel(c.id),
      responsibility: c.responsibility,
      dependsOn: model.relations.filter((r) => r.from === c.id).map((r) => shortTarget(r.to)),
      implements: model.capabilities.filter((cap) => cap.componentIds.includes(c.id)).map((cap) => cap.name),
    })),
    dataModel: (model.dataEntities ?? []).map((e) => ({
      name: e.name,
      ref: refOf(e),
      fields: e.fields
        .filter((f) => !(f.relationTo && !f.isForeignKey))
        .map((f) => ({
          name: f.name,
          type: f.type,
          optional: f.optional,
          list: f.list,
          key: f.isId ? ("PK" as const) : f.isForeignKey ? ("FK" as const) : f.isUnique ? ("UK" as const) : undefined,
        })),
      relations: e.fields
        .filter((f) => f.relationTo)
        .map((f) => ({ field: f.name, to: f.type, list: f.list })),
    })),
    process: proc
      ? { name: proc.name, description: proc.description, steps: proc.tasks.map((t) => t.name) }
      : undefined,
  };
}
